{{- if .Values.persistentvolume.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentvolume.name }}
  labels:
    app: {{ .Values.name }}
spec:
  capacity:
    storage: {{ .Values.persistentvolume.capacity.storage }}
  accessModes:
    {{- toYaml .Values.persistentvolume.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentvolume.storageClassName | default "" }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentvolume.reclaimPolicy | default "Retain" }}
  {{- with .Values.persistentvolume.volumeSource }}
  {{ . | nindent 2 }}
  {{- end }}
{{- end }}
