---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentvolume.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  accessModes:
    {{- toYaml .Values.persistentvolume.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentvolume.storageClassName | default "" }}
  resources:
    requests:
      storage: {{ .Values.persistentvolumeclaim.resources.requests.storage }}
  {{- if .Values.persistentvolume.enabled }}
  volumeName: {{ .Values.persistentvolume.name }}
  {{- end }}
