{{- if .Values.cluster_role_binding -}}
{{- range $cluster_role_binding := .Values.cluster_role_binding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $cluster_role_binding.name | quote }}
  namespace: {{ $cluster_role_binding.namespace | quote }}
roleRef:
  name: {{ $cluster_role_binding.role_ref.name | quote }}
  apiGroup: {{ $cluster_role_binding.role_ref.api_group | quote }}
  kind: {{ $cluster_role_binding.role_ref.kind | quote }}
subjects:
{{- range $subject := $cluster_role_binding.subjects }}  
- name: {{ $subject.name | quote }}
  namespace: {{ $subject.namespace | quote }}
  kind: {{ $subject.kind | quote }}
{{- end }}
{{- end }}
{{- end -}}
