{{- if .Values.secret -}}
{{- $secret := .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | quote }}
  namespace: {{ $secret.namespace | quote }}
  annotations:
    {{- range $key, $value := $secret.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: {{ $secret.type }}
{{- if $secret.data }}
data: {{ $secret.data | nindent 2 }}
{{- end }}
{{- if $secret.stringData }}
stringData: {{ $secret.stringData | nindent 2 }}
{{- end }}
{{- end -}}