{{- if .Values.service_account -}}
{{- $service_account := .Values.service_account -}}
{{- range $account := $service_account.account -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $account }}
  namespace: {{ $service_account.namespace }}
{{- end }}
{{- end }}
